# Generated by Django 3.1.3 on 2020-11-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201108_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=100),
        ),
    ]
